Add missing `require 'securerandom'`
Maybe this was required by default in previous Ruby versions, but on
2.7.2, we get spec failures like this without the require:

    NameError: uninitialized constant RedisLocks::Semaphore::SecureRandom
      Did you mean?  SecurityError